### PR TITLE
added doc and exact types in struct

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by matbesancon** [comment]
DualProblem can store the exact concrete type of the `ModelLike` at construction

**Comment by guilhermebodin** [comment]
@matbesancon Thanks!

**Comment by guilhermebodin** [comment]
@matbesancon Notice that the `dual_set` function will be in MOI 0.9.0 https://github.com/JuliaOpt/MathOptInterface.jl/blob/52352bc8bdfb1e4e4c09db95ca7f7a223582bb81/src/sets.jl#L56

**Comment by matbesancon** [comment]
Ah got it thanks, another reason for @blegat to merge and release :D

**Pull request merged**
